const users = [
  {
    _id: "Jencol",
    info: {
      avatarUrl:
        "https://images.unsplash.com/photo-1530577197743-7adf14294584?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fHBlcnNvbnxlbnwwfDJ8MHx8&auto=format&fit=crop&w=500&q=60",
      firstName: "Jennyfer",
      lastName: "Collin",
      email: "j@collin.com",
      city: "Shefford",
      province: "Québec",
      country: "Canada",
      language: "French",
    },
    exchange: [
      {
        bookId: "0fefc987-32be-4724-8318-055b85f3cbab",
      },
    ],
    tags: [],
    homeLibrary: [],
    contacts: [],
  },
  {
    _id: "Nick",
    info: {
      avatarUrl:
        "https://images.unsplash.com/photo-1484684096794-03e03b5e713e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjh8fHBlcnNvbnxlbnwwfDJ8MHx8&auto=format&fit=crop&w=500&q=60",
      firstName: "Nicolas",
      lastName: "Collin-Tremblay",
      email: "n@ct.com",
      city: "Shefford",
      province: "Québec",
      country: "Canada",
      language: "Hindi",
    },
    exchange: [
      {
        bookId: "230c4482-ad55-4f40-add5-2bdf498a91a0",
      },
    ],
    tags: [],
    homeLibrary: [],
    contacts: [],
  },
  {
    _id: "Vinny",
    info: {
      avatarUrl:
        "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGVyc29ufGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=500&q=60",
      firstName: "Vincent",
      lastName: "Collin-Tremblay",
      email: "v@ct.com",
      city: "Shefford",
      province: "Québec",
      country: "Canada",
      language: "Spanish",
    },
    exchange: [
      {
        bookId: "b5a1ae89-76c4-4cb1-aa4d-7cd31b539252",
      },
    ],
    tags: [],
    homeLibrary: [],
    contacts: [],
  },
];

const userLibraries = [
  {
    _id: 1,
    userId: "7d75f6a3-4e45-4904-a0f4-05dce2bbf0e4",
    books: [
      {
        _id: "b818af44-e564-43a9-b106-86e51edcfaf8",
        borrowed: false,
        lent: false,
        bookshelf: null,
        category: "non-fiction",
        tags: ["Quebec"],
      },
    ],
  },
];

const books = [
  {
    _id: "b818af44-e564-43a9-b106-86e51edcfaf8",
    isbn: "2-7646-0128-x",
    title: "La bulle d'encre",
    subtitle: null,
    authors: ["Suzanne Jacob"],
    translators: [],
    publisher: "Les Éditions du Boréal",
    collection: "Boréal compact",
    yearOfPublication: 2001,
    firstYearOfPub: null,
    category: "non-fiction",
    tags: ["Quebec"],
    language: "French",
    country: "Canada",
    price: 6,
    imageSrc: "url()",
    pages: 148,
    format: "pocket",
    description: "Blablabla",
    stars: 0,
    comments: [],
    quotes: [],
  },
  {
    _id: "954e0b50-abda-4533-a5c2-bd12a76de1a4",
    isbn: "978-2-7646-2337-4",
    title: "Poussière sur la ville",
    subtitle: null,
    authors: ["André Langevin"],
    translators: [],
    publisher: "Les Éditions du Boréal",
    collection: "Boréal compact",
    yearOfPublication: 2014,
    firstYearOfPub: 1953,
    category: "novel",
    tags: ["Quebec"],
    language: "French",
    country: "Canada",
    price: 7,
    imageSrc: "url()",
    pages: 226,
    format: "pocket",
    description: "Blablabla",
    stars: 0,
    comments: [],
    quotes: [],
  },
  {
    _id: "b818af44-e564-43a9-b106-86e51edcfaf9",
    isbn: "978-2-07-036059-8",
    title: "De sang-froid",
    subtitle: "Récit véridique d'un meurtre multiple et de ses conséquences",
    authors: ["Truman Capote"],
    translators: ["Raymond Girard"],
    publisher: "Gallimard",
    collection: "Folio",
    yearOfPublication: 1966,
    firstYearOfPub: 1965,
    category: "non-fiction",
    tags: ["non-fiction"],
    language: "French",
    country: "USA",
    price: 9,
    imageSrc: "url()",
    pages: 506,
    format: "pocket",
    description: "Blablabla",
    stars: 0,
    comments: [],
    quotes: [],
  },
];

module.exports = { users, books, userLibraries };
